tap "buo/cask-upgrade"
tap "jandedobbeleer/oh-my-posh"

brew "abcde"
brew "aws-vault"
brew "awscli"
brew "bat"
brew "btop"
brew "cd-discid"
brew "coreutils"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "gh"
brew "git-delta"
brew "git"
brew "gnupg"
brew "heroku/brew/heroku"
brew "hexyl"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "libxml2"
brew "libyaml"
brew "mas"
brew "mise"
brew "neovim"
brew "nnn"
brew "oh-my-posh"
brew "p7zip"
brew "prettyping"
brew "ripgrep"
brew "shared-mime-info"
brew "tldr"
brew "unar"
brew "wget"
brew "zoxide"

mas "Amphetamine", id: 937984704
mas "Hue Menu Bar for Philips Hue", id: 1500678169
mas "Keynote", id: 409183694
mas "Menu Bar Controller for Sonos", id: 1357379892
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "WhatsApp", id: 310633997

cask "1password"
cask "1password-cli"
cask "basictex"
cask "chatgpt"
cask "cursor"
cask "dropbox"
cask "firefox"
cask "font-victor-mono-nerd-font"
cask "google-chrome"
cask "iina"
cask "kitty"
cask "localsend"
cask "mac-mouse-fix"
cask "orbstack"
cask "postgres-unofficial"
cask "signal"
cask "tailscale-app"
