tap "heroku/brew", trusted: true
tap "modem-dev/tap"

brew "abcde"
brew "actionlint"
brew "awscli"
brew "bat"
brew "btop"
brew "cd-discid"
brew "coreutils"
brew "elio"
brew "eza"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "figlet"
brew "fzf"
brew "gh"
brew "git"
brew "glow"
brew "gnupg"
brew "herdr"
brew "heroku/brew/heroku", trusted: true
brew "hexyl"
brew "httpie"
brew "hyperfine"
brew "imagemagick"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "libxml2"
brew "libyaml"
brew "mas"
brew "mise"
brew "modem-dev/tap/hunk", trusted: true
brew "neovim"
brew "nnn"
brew "oath-toolkit"
brew "p7zip"
brew "pi-coding-agent"
brew "pkgconf"
brew "pnpm"
brew "poppler"
brew "prettyping"
brew "pure"
brew "ripgrep"
brew "supabase"
brew "temporal"
brew "tldr"
brew "unar"
brew "vivid"
brew "wget"
brew "worktrunk"
brew "yazi"
brew "yt-dlp"
brew "zoxide"
brew "zsh"

mas "1Password for Safari", id: 1569813296
mas "Azure VPN Client", id: 1553936137
mas "Hue Menu Bar for Philips Hue", id: 1500678169
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "NextDNS", id: 1464122853
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "WhatsApp", id: 310633997

cask "1password"
cask "1password-cli"
cask "chatgpt"
cask "claude"
cask "claude-code@latest"
cask "codex"
cask "dropbox"
cask "font-jetbrains-mono"
cask "font-victor-mono"
cask "ghostty"
cask "github"
cask "google-chrome"
cask "iina"
cask "localsend"
cask "mac-mouse-fix"
cask "mullvad-vpn"
cask "openusage"
cask "orbstack"
cask "postgres-app"
cask "signal"
cask "zed"
