onboarding = false

[theme]
name = "gruvbox"
auto_switch = false

[ui]
sidebar_width = 42
sidebar_min_width = 28
sidebar_max_width = 50
sidebar_collapsed_mode = "hidden"
pane_borders = true
pane_gaps = true
show_agent_labels_on_pane_borders = true
agent_panel_sort = "priority"

[ui.sidebar.agents]
rows = [
  ["state_icon", { token = "workspace", fg = "#ebdbb2", bold = true, dim = false }],
  [{ token = "agent", fg = "#fabd2f", dim = false }, { token = "tab", fg = "#d3869b", dim = false }],
]
row_gap = 1

[ui.sidebar.spaces]
rows = [
  ["state_icon", { token = "workspace", fg = "#ebdbb2", bold = true, dim = false }],
  [{ token = "branch", fg = "#d3869b", dim = false }, "git_status"],
]
row_gap = 1

[ui.toast]
delivery = "herdr"
delay_seconds = 2

[ui.sound]
enabled = true
